import { createHash } from 'node:crypto';
import { resolve as resolvePath } from 'node:path';
import { flag, parseCommandArgs, stringOption } from '../args.js';
import { loadCertificateIdentity } from '../certificate.js';
import type { Command, CommandContext } from '../command.js';
import { guidedOperatorDriver } from '../conformance/drivers.js';
import { runConformance } from '../conformance/runner.js';
import type { ConformanceSessionFile, SyntheticDevices } from '../conformance/types.js';
import { createDoctorTransport } from '../doctor/graph.js';
import { checkOrigin, redactOrigin } from '../doctor/origin.js';
import {
  EXIT_CHECKS_FAILED,
  EXIT_OK,
  OperationalError,
  UsageError,
  type ExitCode,
} from '../errors.js';
import { EXIT_CODE_HELP, REPORT_HELP } from '../help.js';
import { renderReport } from '../report/render.js';
import { ReportBuilder, serializeReport } from '../report/report.js';
import type { TargetMode } from '../report/types.js';
import { DEFAULT_DEVICE_CAPABILITY_PATH } from './doctor.js';

const USAGE = 'conformance <origin> [options]';
const DEFAULT_SESSION_FILE = '.fortress-csip-session.json';

/**
 * Exercise the Fortress polling profile end to end.
 *
 * Explicitly mutating, in contrast to `doctor`: it registers EndDevices, posts responses, and
 * publishes telemetry. Everything it creates is synthetic and derived by the toolkit, so no
 * real site identity is ever sent and no partner is asked to hand Fortress a device roster.
 *
 * Two checks need the partner's own operator tooling — assigning a device to a program, and
 * publishing a control. The command generates precise instructions for those and then polls
 * the connection for the result, rather than requiring a Fortress-specific admin endpoint.
 */
export function conformanceCommand(): Command {
  return {
    name: 'conformance',
    arguments: '<origin> [options]',
    summary: 'Exercise the Fortress polling profile and produce evidence',
    help: () =>
      [
        `fortress-csip ${USAGE}`,
        'fortress-csip conformance --self-test [options]',
        '',
        'Run the Fortress polling profile against your IEEE 2030.5 server and write a',
        'sanitized evidence artifact to attach to your Fortress handoff.',
        '',
        'Unlike doctor, this command mutates: it registers two synthetic EndDevices,',
        'posts lifecycle responses, and publishes telemetry. Every identity it uses is',
        'generated by the toolkit — no real site identity is sent, and no device roster',
        'is exchanged out of band.',
        '',
        'Options:',
        '  --self-test            Run against the bundled example server, with no endpoint',
        '  --cert PATH            Client certificate to authenticate with',
        '  --key PATH             Private key for that certificate',
        '  --ca PATH              Extra trust root (requires --local)',
        '  --local                Loopback rehearsal: permits --ca and a non-443 port',
        `  --path PATH            DeviceCapability path (default ${DEFAULT_DEVICE_CAPABILITY_PATH})`,
        `  --session PATH         Resumable session state (default ${DEFAULT_SESSION_FILE})`,
        '  --wait-minutes N       How long to wait for each operator action (default 10)',
        '  --keep-test-devices    Leave the synthetic EndDevices in place for investigation',
        '',
        ...REPORT_HELP,
        '',
        'Two steps need your own operator tooling: assigning one test device to a',
        'DERProgram, and publishing one bounded rehearsal control. The command prints',
        'exactly what to do and then watches the connection — it never requires you to',
        'expose an administrative API to Fortress.',
        '',
        'The session file makes a run resumable, so pausing for an operator action does',
        'not force re-registration. It holds synthetic identities and check state only,',
        'never your private key.',
        '',
        'Examples:',
        '  fortress-csip conformance --self-test --out ./conformance-self-test.json',
        '  fortress-csip conformance https://csip.partner.example \\',
        '      --cert ./test-client.pem --key ./test-client.key \\',
        '      --out ./fortress-csip-evidence.json',
        '',
        ...EXIT_CODE_HELP,
      ].join('\n'),
    run: async (argv: string[], context: CommandContext): Promise<ExitCode> => {
      const { values, positionals } = parseCommandArgs('conformance', argv, {
        'self-test': { type: 'boolean' },
        cert: { type: 'string' },
        key: { type: 'string' },
        ca: { type: 'string' },
        local: { type: 'boolean' },
        path: { type: 'string' },
        session: { type: 'string' },
        'wait-minutes': { type: 'string' },
        'keep-test-devices': { type: 'boolean' },
        json: { type: 'boolean' },
        out: { type: 'string' },
      });

      const selfTest = flag(values, 'self-test');
      const asJson = flag(values, 'json');
      const outPath = stringOption(values, 'out', 'conformance');
      const deviceCapabilityPath =
        stringOption(values, 'path', 'conformance') ?? DEFAULT_DEVICE_CAPABILITY_PATH;
      const absolute = (path: string) => resolvePath(context.io.cwd, path);

      if (selfTest && positionals.length > 0) {
        throw new UsageError('--self-test takes no origin: it runs against the bundled server', 'conformance');
      }
      if (!selfTest && positionals.length !== 1) {
        throw new UsageError(
          `conformance requires an origin, or --self-test\n  usage: fortress-csip ${USAGE}`,
          'conformance',
        );
      }

      const waitMinutes = parseWaitMinutes(stringOption(values, 'wait-minutes', 'conformance'));
      const sessionPath = absolute(stringOption(values, 'session', 'conformance') ?? DEFAULT_SESSION_FILE);
      const keepTestDevices = flag(values, 'keep-test-devices');

      const origin = selfTest ? 'self-test' : positionals[0];
      const report = new ReportBuilder('conformance', {
        origin: selfTest ? 'bundled-example-server' : redactOrigin(origin),
        deviceCapabilityPath,
        mode: selfTest || flag(values, 'local') ? 'local' : 'deployed',
      });

      const session = await loadSession(context, sessionPath, origin);
      const persist = async (updated: ConformanceSessionFile): Promise<void> => {
        await context.io.writeFileAtomic(sessionPath, `${JSON.stringify(updated, null, 2)}\n`);
      };

      if (selfTest) {
        await runSelfTest(context, report, session, persist, {
          deviceCapabilityPath,
          keepTestDevices,
        });
      } else {
        const exitEarly = await runRemote(context, report, session, persist, {
          origin,
          deviceCapabilityPath,
          values,
          waitMinutes,
          keepTestDevices,
          absolute,
        });
        if (exitEarly !== undefined) return exitEarly;
      }

      const built = report.build(context.io.now());
      const serialized = serializeReport(built);
      if (asJson) {
        context.io.out(serialized.trimEnd());
      } else {
        renderReport(built, context.io);
      }
      if (outPath !== undefined) {
        await context.io.writeFileAtomic(absolute(outPath), serialized);
        if (!asJson) context.io.out(`Evidence written to ${outPath}`);
      }
      return built.summary.fail > 0 ? EXIT_CHECKS_FAILED : EXIT_OK;
    },
  };
}

async function runSelfTest(
  context: CommandContext,
  report: ReportBuilder,
  session: ConformanceSessionFile,
  persist: (session: ConformanceSessionFile) => Promise<void>,
  options: { deviceCapabilityPath: string; keepTestDevices: boolean },
): Promise<void> {
  const { startSelfTestFixture } = await import('../conformance/self-test.js');
  context.io.err('Starting the bundled production-shaped example server...');
  const fixture = await startSelfTestFixture(context.io);
  try {
    context.io.err(`Self-test server listening on ${fixture.origin}`);
    context.io.err('');
    await runConformance({
      transport: fixture.transport,
      report,
      io: context.io,
      driver: fixture.driver,
      devices: session.devices,
      session,
      persist,
      sleep: context.sleep,
      keepTestDevices: options.keepTestDevices,
    });
  } finally {
    await fixture.close();
  }
}

async function runRemote(
  context: CommandContext,
  report: ReportBuilder,
  session: ConformanceSessionFile,
  persist: (session: ConformanceSessionFile) => Promise<void>,
  options: {
    origin: string;
    deviceCapabilityPath: string;
    values: Record<string, string | boolean | undefined>;
    waitMinutes: number;
    keepTestDevices: boolean;
    absolute: (path: string) => string;
  },
): Promise<ExitCode | undefined> {
  const { values, absolute } = options;
  const mode: TargetMode = flag(values, 'local') ? 'local' : 'deployed';
  const certPath = stringOption(values, 'cert', 'conformance');
  const keyPath = stringOption(values, 'key', 'conformance');
  const caPath = stringOption(values, 'ca', 'conformance');

  if (caPath !== undefined && mode !== 'local') {
    throw new UsageError(
      '--ca is permitted only with --local: a deployed connection uses the standard public trust store',
      'conformance',
    );
  }
  if (certPath === undefined || keyPath === undefined) {
    throw new UsageError(
      'remote conformance requires --cert and --key: the profile is exercised as an authenticated client',
      'conformance',
    );
  }

  // The transport rules are the same ones doctor enforces; a run against an origin that
  // fails them would be proving conformance of something Fortress would refuse to talk to.
  const parsed = await checkOrigin(options.origin, mode, report, context.resolveHost);
  if (parsed === undefined || !report.healthy) {
    context.io.err('The origin did not pass the transport checks; run `fortress-csip doctor` for detail.');
    return undefined;
  }

  const certificate = await read(context, absolute(certPath));
  const privateKey = await read(context, absolute(keyPath));
  const identity = await loadCertificateIdentity(absolute(certPath), async () => certificate);
  report.setIdentity({
    aggregatorLfdi: identity.aggregatorLfdi,
    certificateFingerprintSha256: identity.fingerprintSha256,
    certificateNotAfter: identity.notAfter.toISOString(),
  });

  const transport = createDoctorTransport({
    origin: parsed.url.origin,
    deviceCapabilityPath: options.deviceCapabilityPath,
    mode,
    certificate,
    privateKey,
    certificateAuthorities:
      caPath === undefined ? undefined : [await read(context, absolute(caPath))],
  });

  try {
    await runConformance({
      transport,
      report,
      io: context.io,
      driver: guidedOperatorDriver(context.io, { pollTimeoutMs: options.waitMinutes * 60_000 }),
      devices: session.devices,
      session,
      persist,
      sleep: context.sleep,
      keepTestDevices: options.keepTestDevices,
    });
  } finally {
    transport.close?.();
  }
  return undefined;
}

/**
 * Load or create the resumable session.
 *
 * A session belongs to one origin: silently reusing a session recorded against a different
 * server would resume with EndDevices that do not exist there, and produce a confusing run
 * rather than an honest one.
 */
async function loadSession(
  context: CommandContext,
  path: string,
  origin: string,
): Promise<ConformanceSessionFile> {
  const now = context.io.now().toISOString();
  let existing: ConformanceSessionFile | undefined;
  try {
    const raw = await context.io.readFile(path);
    existing = JSON.parse(Buffer.from(raw).toString('utf8')) as ConformanceSessionFile;
  } catch {
    existing = undefined;
  }

  if (existing !== undefined && existing.origin === origin && existing.devices !== undefined) {
    context.io.err(`Resuming the conformance session recorded in ${path}.`);
    return { ...existing, updatedAt: now };
  }
  if (existing !== undefined && existing.origin !== origin) {
    context.io.err(
      `${path} was recorded against a different origin; starting a fresh session.`,
    );
  }

  return {
    schema: 'fortress-csip-conformance-session/v1',
    createdAt: now,
    updatedAt: now,
    origin,
    devices: syntheticDevices(origin, now),
  };
}

/**
 * Derive the two synthetic test identities.
 *
 * They are a deterministic function of the origin and the session's creation time, so a
 * resumed run reuses them and two concurrent sessions do not collide. They are LFDI-shaped
 * because that is what the protocol expects, but they identify nothing: no real site, no
 * customer, and no device that exists anywhere.
 */
export function syntheticDevices(origin: string, seed: string): SyntheticDevices {
  const derive = (label: string): string =>
    createHash('sha256')
      .update(`fortress-csip:conformance-synthetic\0${origin}\0${seed}\0${label}`)
      .digest('hex')
      .slice(0, 40);
  return {
    alpha: { lfdi: derive('alpha'), label: 'test-device-alpha' },
    beta: { lfdi: derive('beta'), label: 'test-device-beta' },
  };
}

function parseWaitMinutes(raw: string | undefined): number {
  if (raw === undefined) return 10;
  const value = Number(raw);
  if (!Number.isSafeInteger(value) || value <= 0 || value > 120) {
    throw new UsageError('--wait-minutes must be a whole number of minutes between 1 and 120', 'conformance');
  }
  return value;
}

async function read(context: CommandContext, path: string): Promise<Uint8Array> {
  try {
    return await context.io.readFile(path);
  } catch (error) {
    throw new OperationalError(
      `could not read ${path}: ${(error as Error).message}`,
      'Check the path and that the file is readable by this user.',
    );
  }
}
