// Generates the expanded telemetry catalog from Fortress's SunSpec 40k/42k point
// dictionary (`scripts/catalog-sources/`). Emits:
//   - packages/protocol/src/catalog.generated.ts   (logic fields, for client/server)
//   - packages/example-server/public/console/catalog-data.js  (display fields, for the console)
// Curated entries in catalog.ts win on fortressPoint collisions; the generator only
// produces extension-lane (off-spec) entries.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const csv = readFileSync(root + 'scripts/catalog-sources/ss40k_ss42k_point_definitions.csv', 'utf8');

function parseCsv(text) {
  const rows = []; let row = []; let cur = ''; let q = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (q) {
      if (ch === '"' && text[i + 1] === '"') { cur += '"'; i++; }
      else if (ch === '"') q = false;
      else cur += ch;
    } else if (ch === '"') q = true;
    else if (ch === ',') { row.push(cur); cur = ''; }
    else if (ch === '\n' || ch === '\r') {
      if (ch === '\r' && text[i + 1] === '\n') i++;
      row.push(cur); cur = '';
      if (row.length > 1 || row[0] !== '') rows.push(row);
      row = [];
    } else cur += ch;
  }
  if (cur !== '' || row.length) { row.push(cur); rows.push(row); }
  const head = rows[0];
  return rows.slice(1).map((cells) => Object.fromEntries(head.map((h, i) => [h, cells[i] ?? ''])));
}

// IEEE 2030.5 Annex A UomType (subset) — map the dictionary's unit string to a uom code.
const UOM = { W: 38, kW: 38, V: 29, mV: 29, A: 5, mA: 5, Hz: 33, var: 63, VA: 61, Wh: 72, kWh: 72, PF: 65, '%': 0, 'N/A': 0, '': 0 };
const uomOf = (u) => UOM[u] ?? UOM[String(u).toLowerCase()] ?? 0;
const scaleOf = (u) => ({ kW: 3, kWh: 3, mA: -3, mV: -3 }[u] ?? 0); // 10^3 kilo, 10^-3 milli

// The dictionary's `labels` column carries FMP's classification as "Family: Value" pairs
// (separated by | or ;) — e.g. "Level of Detail: Complete; Component: Battery; ...".
function parseLabels(s) {
  const o = {};
  for (const part of String(s || '').split(/\s*[|;]\s*/)) {
    const i = part.indexOf(':');
    if (i > 0) o[part.slice(0, i).trim()] = part.slice(i + 1).trim();
  }
  return o;
}
// FMP-style cruft filter: real telemetry carries classification labels; structural registers
// (scale factors *_SF, model headers ID/L, reserved/serial/site-id) are unlabeled — drop them,
// exactly the points FMP hides. The pattern also catches the few labeled stragglers (siteID).
const STRUCTURAL = /(^id$|^l$|_sf$|^sf$|^site\s?id$|^reserved\d*$|^sn$|^mn$)/i;
const LOD = { standard: 'standard', extended: 'extended', complete: 'complete' };

const rows = parseCsv(csv);
const logic = [];   // catalog.generated.ts
const display = [];  // catalog-data.js
let dropped = 0;
for (const r of rows) {
  const model = Number(r.model);
  if (!model) continue;
  const point = (r.point || '').trim();
  if (!r.labels || !r.labels.trim() || STRUCTURAL.test(point)) { dropped++; continue; }   // FMP cruft drop
  const labels = parseLabels(r.labels);
  const fortressPoint = `model${model}.${point}`;
  const mrid = `fortress:${model}-${point}`.toLowerCase();
  const uom = uomOf(r.unit);
  const scale = scaleOf(r.unit);
  const category = labels['Component'] || r.category || 'Other';                            // FMP Component grouping (not "SunSpec NNNNN")
  const levelOfDetail = LOD[(labels['Level of Detail'] || '').toLowerCase()] || 'complete';
  const equipment = labels['Equipment'] || undefined;
  const mapping = { kind: 'extension', uom, conventionMrid: mrid };
  // logic entry (protocol): modelId kept internally for traceability — NOT surfaced as SunSpec.
  logic.push({ fortressPoint, sunspec: { modelId: model, block: r.block || undefined }, tier: 'off-spec', mapping, scale, category, levelOfDetail });
  // display entry (console): no model/SunSpec field — grouped by Component, gated by Level of Detail.
  display.push({ fortressPoint, display: r.description || r.name || point, desc: r.longdescription || r.description || '', unit: r.unit === 'N/A' ? '' : r.unit, scale, tier: 'off-spec', mapping, category, levelOfDetail, equipment });
}

writeFileSync(
  root + 'packages/protocol/src/catalog.generated.ts',
  `// GENERATED by scripts/gen-catalog.mjs — do not edit by hand.\n` +
  `import type { CatalogEntry } from './catalog.js';\n` +
  `export const GENERATED_CATALOG: CatalogEntry[] = ${JSON.stringify(logic, null, 0)};\n`,
);
writeFileSync(
  root + 'packages/example-server/public/console/catalog-data.js',
  `/* GENERATED by scripts/gen-catalog.mjs — do not edit by hand. */\n` +
  `window.FP_GENERATED = ${JSON.stringify(display, null, 0)};\n`,
);
console.log(`gen-catalog: ${logic.length} classified 40k/42k points kept, ${dropped} cruft dropped → catalog.generated.ts + catalog-data.js`);
